### ISSUE TITLE
New LOLIN ESP32 board called S2 mini

### ISSUE THREAD

**Issue by lcsjunior** [r0oland/ESP32_mini_KiCad_Library#3]
[https://www.wemos.cc/en/latest/s2/s2_mini.html](https://www.wemos.cc/en/latest/s2/s2_mini.html)

Is it the same pinout?

**Comment by r0oland** [comment]
Comparing the board layout with the images in the repo I'd say nope. 

S2 Mini seems to have 8 pins per row, the pinout here has 10. Plus it's a different chip, so pretty sure that's a no.
