### ISSUE TITLE
Add Lilon S2 mini?

### ISSUE THREAD

**Issue by martin072** [r0oland/ESP32_mini_KiCad_Library#5]
Hi,

Great work. Would it be possible to add the Lolin S2 (-or C3) Mini? It is 100% pin compatible with the D1 Mini?

See here: [https://www.wemos.cc/en/latest/s2/s2_mini.html](url)

**Comment by r0oland** [comment]
I am sorry, but I don't have time at the moment. If it's pin compatible to the ESP32 mini (check here for example 
![image](https://user-images.githubusercontent.com/558053/185424277-3696ba42-a791-4c4e-bba7-6ad58f5ca2bc.png)) then I am happy to add a short info in the repo. If not, you could use this as a basis and create a pull request which I am happy to merge.

**Comment by martin072** [comment]
It is pin compatible with the D1 mini, however the S2 has only 8 pins (well double rows though), like the D1  and not ten then on the device you're showing. So it requires a new layout as the double rows of pins ar now on the inside, not the outside as on your above picture. 

The S2 is therefore also in dimensions 100% D1 Mini compatible, making it a extremely nice substitute to the D1 if you have existing PCB's

I am able to modify the Symbol (based on the original ESP32 S2 chip, removed all the pins that have no output on the LOLIN board), but not really understand how to change the PCB layout 


<img width="731" alt="Screenshot 2022-08-19 at 17 09 45" src="https://user-images.githubusercontent.com/24524506/185637218-8c3fa601-0162-449e-b383-0fa7c15ac7c4.png">

[lolin-s2mini.kicad_sym.zip](https://github.com/r0oland/ESP32_mini_KiCad_Library/files/9383042/lolin-s2mini.kicad_sym.zip)

**Comment by r0oland** [comment]
Like I wrote, I won't have the time to do any changes to the layout at the moment. But it's not hard to do yourself, so feel free to make the required changes and open a pull request.

**Comment by martin072** [comment]
Ok, will close the issue. Thanks for the quick reply's
